### ISSUE TITLE
Add support to export by tag

### ISSUE THREAD

**Issue by extmkv** [hyperdevs-team/poeditor-android-gradle-plugin#22]
**Summary and context of the enhancement**
As an user I want to download the strings for specific module based on a given tag(s).

**Suggested implementation**
Added a new configuration to the poEditor receiving an array of tags.
On the poEditor API request send the list of tags to poEditor API, poEditor will filter the strings by tag(s)

[Export Documentation](https://poeditor.com/docs/api#projects_export)

**Comment by adriangl** [comment]
Hi! I apologize for the late reply. I've got this more or less implemented, let me finish the implementation and I'll get back at you.
