### ISSUE TITLE
Simplified and Traditional Chinese are downloaded to folders not accepted by Android

### ISSUE THREAD

**Issue by markuskallander** [hyperdevs-team/poeditor-android-gradle-plugin#25]
**SW details (please complete the following information):**
 - Plug-in Version 1.4.1

------------------------------------------------------------
Gradle 6.2
------------------------------------------------------------

Build time:   2020-02-17 08:32:01 UTC
Revision:     61d3320259a1a0d31519bf208eb13741679a742f

Kotlin:       1.3.61
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          1.8.0_231 (Oracle Corporation 25.231-b11)
OS:           Mac OS X 10.16 x86_64

**Summary and background of the bug**
Simplified Chinese is downloaded to `values-zh-rHANS` and Traditional Chinese to `values-zh-tHANT`. They should probably be in `values-b+zh+Hans` and `values-b+zh+Hant` respectively.

**Steps to reproduce**
1. Add languages Simplified Chinese and Traditional Chinese to your POEditor project
2. Download translations using this gradle plugin

**Expected behavior**
Translations should probably be in `values-b+zh+Hans` and `values-b+zh+Hant` respectively.

**Current behavior**
Simplified Chinese is downloaded to `values-zh-rHANS` and Traditional Chinese to `values-zh-tHANT`

**Comment by adriangl** [comment]
Hi! I apologize for the late reply, we'll take a look at the issue ASAP!

**Comment by adriangl** [comment]
Hmmm, I've been checking the issue and the proposed solution seems to only be working for Android 7 onwards, so I'd rather try to offer a solution for at least Android 5 onwards for said languages.

I've got to check this in detail before adding a proper solution. These articles shed some light into the resources that the plugin can use to resolve this:
* https://gist.github.com/amake/0ac7724681ac1c178c6f95a5b09f03ce
* https://medium.com/googleplaydev/demystifying-chinese-languages-in-the-app-world-b2a4e7dd1276

**Comment by Julien-corazza** [comment]
Hi! Is there any update on this matter?
I tried to use something like his in my config:
```
languageValuesOverridePathMap = [
            "zh-Hans" : "${rootDir}/app/src/res/values-zh",
    ]
```
But it doesn't create values-zh folder. It just stops importing zh-Hans language.
I'm using 2.2.1 version.

**Comment by adriangl** [comment]
Hi @markuskallander!
Not sure if you still need this, but could you take a look at #54?

Thanks!
