### ISSUE TITLE
java.net.SocketTimeoutException while downloading translations xml file

### ISSUE THREAD

**Issue by rafid059** [hyperdevs-team/poeditor-android-gradle-plugin#29]
**SW details (please complete the following information):**
 - IDE version: any version, also CI
 - Plug-in Version latest version, master, previous versions

**Summary and background of the bug**
The task `importPoEditorStrings` fails more than once for all devs with `java.net.SocketTimeoutException`. This happens way too often and also on CI which breaks our builds.

**Steps to reproduce**
1. I set up the configuration
2. I run the task
3. See the socket timeout error at least once per day

Not-so-helpful stack trace:
```
* What went wrong:

Execution failed for task ':data-translations:importPoEditorStrings'.

> java.net.SocketTimeoutException: timeout
```

**Expected behavior**
Translations should download unless the server is actually down

**Current behavior**
Task fails to download translations quite often due to SocketTimeoutException

**Additional context**

**Comment by rafid059** [comment]
I'd suggest to increase the read timeout parameter for okhttpclient [here](https://github.com/hyperdevs-team/poeditor-android-gradle-plugin/blob/master/src/main/kotlin/com/hyperdevs/poeditor/gradle/PoEditorStringsImporter.kt#L49) to maybe 25 or 30 seconds. Wdyt?

**Comment by adriangl** [comment]
Yup, it may be a good idea. 
I haven't had any timeout issues in my usual workflow, but it may come in handy in a lot of other use cases (such as yours). I'll take a look and notify you as soon as I have it!
