### ISSUE TITLE
Remove/Skip untranslated strings from XML

### ISSUE THREAD

**Issue by TenSeventy7** [hyperdevs-team/poeditor-android-gradle-plugin#32]
**Summary and context of the enhancement**
When importing translations from POEditor, terms that are currently not translated to a given language must be removed.

Android Studio/Gradle's default behavior on blank but defined strings is to actually blank the text out instead of using the default (from values). This causes the app to crash, notably if it uses placeholders.

**Comment by adriangl** [comment]
Hi @TenSeventy7!

In version 2.4.0 of the plug-in, you can now use the `filters` parameter to filter untranslated strings. Hope you find it useful and let me know if it works for you!
