### ISSUE TITLE
Migrate to POEditor API v2

### ISSUE THREAD

**Issue by nokite** [hyperdevs-team/poeditor-android-gradle-plugin#39]
**Summary and context of the enhancement**
API v1 has been deprecated, so we need to migrate to v2.

**Suggested implementation**
- Change the base URL from `https://poeditor.com/api/` to `https://api.poeditor.com/v2/` and adapt the data model, endpoints etc according to the new API. 
- Make sure they update the info about the plugin here: https://poeditor.com/help/user_contributions

**Additional documentation**
https://poeditor.com/docs/api

**Comment by adriangl** [comment]
Hi @nokite!
Thanks for reminding me to do it! Please check #40 for the migration PR :D
