### ISSUE TITLE
Html based strings wrapped by <![CDATA[ ]]> on POEditor are imported without <![CDATA[ ]]> via plugin

### ISSUE THREAD

**Issue by awachowicz-futuremind** [hyperdevs-team/poeditor-android-gradle-plugin#44]
**SW details**
 - IDE version: Android Studio Arctic Fox 2020.3.1
 - Plug-in Version: 2.2.1 - 2.4.0

**Summary and background of the bug**
Html based strings wrapped by `<![CDATA[ ]]>` on POEditor are imported without  `<![CDATA[ ]]>` via plugin 

**Steps to reproduce**
1. Add html based string to POEditor project 
e.g: `<![CDATA[Some text<a href="%1$s">Link</a> text text]]>`
2. Import the strings in to project
3. `<![CDATA[ ]]>` is missed 
e.g:
`<string name="test_string_id">"Some text<a href="%1$s">Link</a> text text"</string>`

**Expected behavior**
Imported strings should contain `<![CDATA[ ]]>` 

**Current behavior**
`<![CDATA[ ]]>` is missed 

**Additional context**
When strings are exported via POEditor web page, they contain `<![CDATA[ ]]>`

**Comment by adriangl** [comment]
Hi @awachowicz-futuremind! The issue should be solved in #46, please check it out!
