### ISSUE TITLE
Remove JCenter before February 2022

### ISSUE THREAD

**Issue by nokite** [hyperdevs-team/poeditor-android-gradle-plugin#48]
**SW details:**
 - Plug-in Version 2.4.1
 
**Summary and background of the bug**
JCenter may stop working in February 2022, so it should be removed from the project. Any dependencies should be fetched from other repositories.

The shutdown date of the repository itself is not clear. In reality it might keep working in read-only mode for a longer time. But no guarantees are given after February. 
Furthermore, Gradle 8 will remove jcenter().

https://blog.gradle.org/jcenter-shutdown

**Comment by adriangl** [comment]
Done! I also needed to upgrade detekt to the latest version so I could remove jcenter completely.
Thanks for the reminder @nokite!

**Comment by nokite** [comment]
Nice, so quick! Thanks!
