### ISSUE TITLE
Build fail after Android Gradle Plugin 7.1.0 update

### ISSUE THREAD

**Issue by orgeslayer** [hyperdevs-team/poeditor-android-gradle-plugin#50]
**SW details (please complete the following information):**
 - IDE version: Android Studio Bumbebee 1.1.0
 - Plug-in Version: 2.4.2

**Summary and background of the bug**

![image](https://user-images.githubusercontent.com/19642747/151468290-7814d512-656a-4b61-bc91-aceba6111bbe.png)

After updating the android gradle plugin from 7.0.4 to 7.1.0,  an error occurs when building.
I think ApplicationAndroidComponentsExtension was deprecated.
- https://developer.android.com/reference/tools/gradle-api/7.0/com/android/build/api/extension/ApplicationAndroidComponentsExtension

**Steps to reproduce**
1. Android Gradle Plugin "com.android.tools.build:gradle:7.1.0" update
2. Build

**Comment by adriangl** [comment]
Hi @orgeslayer !
Thanks for the report! Check #50 if you can ;)
