### ISSUE TITLE
Indonesian is exported to values-id instead of values-in

### ISSUE THREAD

**Issue by Yanndroid** [hyperdevs-team/poeditor-android-gradle-plugin#56]
The strings.xml file for Indonesian is exported to `values-id` but changing the device language to Indonesian has no effect on the app. If the file is in `values-in` however, it works as expected.
Another thing I noticed is that both `id` and `in` are listed as Indonesian in Android Studio's Translations Editor, but on the phone itself only `in` is working. This seems to be more of a Java/Android issue, since the official ISO 639-1 is in fact `id`.

I think this is also the case for Hebrew and Yiddish: https://developer.android.com/reference/java/util/Locale.html#Locale(java.lang.String)

> ISO 639 is not a stable standard; some of the language codes it defines (specifically "iw", "ji", and "in") have changed. This constructor accepts both the old codes ("iw", "ji", and "in") and the new codes ("he", "yi", and "id"), but all other API on Locale will return only the OLD codes.

 - IDE version: Android Studio 2021.2.1
 - Plug-in Version: 3.0.0
 - Android version: 12

**Comment by adriangl** [comment]
Hello! Thanks for the detailed report!

I'll take a look at it, it should be easy to fix ;)
