### ISSUE TITLE
Multiply projects support

### ISSUE THREAD

**Issue by alzakharenk** [hyperdevs-team/poeditor-android-gradle-plugin#60]
**Support for several poeditor project ids**
We have split all our strings to several poeditor projects - analytics, links, common strings. It will be great to support several projectId's in configuration.

**Comment by adriangl** [comment]
Hello @alzakharenk!

We discarded adding support for multiple projects some time ago, you can read more about this at: https://github.com/hyperdevs-team/poeditor-android-gradle-plugin/issues/43#issuecomment-889946084

Regards
