### ISSUE TITLE
Setting order is not working

### ISSUE THREAD

**Issue by carlosrivin** [hyperdevs-team/poeditor-android-gradle-plugin#61]
**SW details (please complete the following information):**
 - IDE version: Android Studio Flamingo v9
 - Plug-in Version - 3.1.0

**Summary and background of the bug**
In the documentation it's mentioned that it's possible to send order in the parameters but I belive in the latest gradle settings it's not working because it's missing a setter. Something like this for example:
fun setDefaultLang(value: String) = defaultLang.set(value)

This is not available for order

**Steps to reproduce**
1. Add the "order = "terms"" in the poEditor block.
2. Sync the project
3. See error

A problem occurred evaluating project ':app'.
> Could not set unknown property 'order' for extension 'poEditor' of type com.hyperdevs.poeditor.gradle.PoEditorPluginExtension.

**Expected behavior**
Value would be set in the request to poeditor and terms would arrive ordered

**Current behavior**
Crashes. Exception in pasted above.

**Additional context**
Nothing else.

**Comment by adriangl** [comment]
Hi @carlosrivin!

Thanks for the report, I must have missed the setter creation when code reviewing the PR that introduced the parameter, sorry!

It should now be fixed in #62, please let me know if it works ;)

**Comment by carlosrivin** [comment]
the fix worked! :)

side question. Is there a way to send this options parameter so that I can request it without quotes? I find it odd this quotes default way.

Link about it: https://poeditor.com/kb/quotes-in-android-string-resources
