### ISSUE TITLE
Multiple tags intersection doesn't work

### ISSUE THREAD

**Issue by bogdanzurac** [hyperdevs-team/poeditor-android-gradle-plugin#69]
**SW details (please complete the following information):**
 - IDE version: AS Giraffe
 - Plug-in Version 3.4.1

**Summary and background of the bug**
Tags intersection doesn't work when specifying a list of tags. The plugin just pulls in all strings, not an intersection of the tags as it's supposed to.

I assume this is caused by the way the tags are being sent using Retrofit. They should be sent as `tags : ["tagA", "tagB"]` (https://poeditor.com/docs/api#projects_export_example_1_button). I haven't been able to check it, but I assume currently they are being sent as `tags : tagA, tagB`

**Steps to reproduce**
1. Set up 2 strings on the PoEditor web app using 3 tags (string 1 being added to tags A & B, string 2 being added to tags A & C)
2. Set up the plugin config to pull in tags A & B
3. Run the import

**Expected behavior**
Only string 1 should be pulled.

**Current behavior**
Currently both strings are pulled.

**Comment by bogdanzurac** [comment]
I've tried a fix for this in #70. Haven't tested it as I'm not familiar with the testing procedure in this repo. Please double check the changes before merging.

**Comment by adriangl** [comment]
The fix will be released in version `3.4.2` ;)
